apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-dev-productpage
  namespace: student48-bookinfo-dev
  labels:
    app: bookinfo-dev-productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-dev-productpage
  template:
    metadata:
      labels:
        app: bookinfo-dev-productpage
    spec:
      containers:
      - name: bookinfo-dev-productpage
        image: ghcr.io/62130500119/bookinfo-productpage:dev
        imagePullPolicy: Always
        env:
        - name: RATINGS_HOSTNAME
          value: http://sitkmutt.bookinfo.dev.opsta.net/student48/ratings
        - name: DETAILS_HOSTNAME
          value: http://sitkmutt.bookinfo.dev.opsta.net/student48/details
        - name: REVIEWS_HOSTNAME
          value: http://sitkmutt.bookinfo.dev.opsta.net/student48/reviews
      imagePullSecrets:
      - name: registry-bookinfo