productpage:
  namespace: student48-bookinfo-prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8083
  image: ghcr.io/62130500119/bookinfo-productpage
  tag: prd
ingress:
  host: sitkmutt.bookinfo.opsta.net
  path: "/student48/productpage(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  RATINGS_HOSTNAME: http://sitkmutt.bookinfo.opsta.net/student48/ratings
  DETAILS_HOSTNAME: http://sitkmutt.bookinfo.opsta.net/student48/details
  REVIEWS_HOSTNAME: http://sitkmutt.bookinfo.opsta.net/student48/reviews
